version: "3.8"
services:
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  data: { }

networks:
  default:
    name: mongo-network