server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/etraveli_db?useSSL=false
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: refactoring-java
        url: /v3/api-docs