spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: etraveli
    password: password
  h2:
    console:
      enabled: true

bonusPoints:
  applicableDays: 2
  applicableGenre: "NEW"

base:
  frequentEntrePoints: 1